# Generated by Django 4.2 on 2023-09-06 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cursos_instituicao_remove_venda_funcionario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instituicao',
            name='telefone',
            field=models.CharField(max_length=11),
        ),
    ]
