# Generated by Django 4.2 on 2023-09-08 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_instituicao_telefone'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursos',
            name='categoria',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='instituicao',
            name='email',
            field=models.EmailField(blank=True, max_length=11, null=True),
        ),
    ]
