# Generated by Django 4.2 on 2023-09-08 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_cursos_categoria_instituicao_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instituicao',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
    ]
