# Generated by Django 4.2.6 on 2023-11-01 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_cursos_data_de_criacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursos',
            name='categoria',
            field=models.CharField(blank=True, choices=[('culinaria', 'Culinaria'), ('danca', 'Dança'), ('esportes', 'Esportes')], max_length=10, null=True),
        ),
    ]
