# Generated by Django 4.2.6 on 2023-11-01 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_cursos_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursos',
            name='categoria',
            field=models.CharField(choices=[('categoria1', 'Categoria 1'), ('categoria2', 'Categoria 2'), ('categoria3', 'Categoria 3')], default='categoria1', max_length=50),
        ),
    ]
