# Generated by Django 4.2.6 on 2023-11-01 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_cursos_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursos',
            name='categoria',
            field=models.CharField(choices=[('culinaria', 'Culinária'), ('danca', 'Dança'), ('esportes', 'Esportes'), ('idiomas', 'Idiomas'), ('musica', 'Música'), ('negocios', 'Negócios'), ('tecnologia', 'Tecnologia'), ('artes', 'Artes'), ('outros', 'Outros')], default='categoria1', max_length=50),
        ),
    ]
