# Generated by Django 4.2 on 2023-09-23 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_estudante'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudante',
            name='celular',
        ),
    ]
