# Generated by Django 4.2 on 2023-09-27 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_delete_categorias'),
    ]

    operations = [
        migrations.AddField(
            model_name='instituicao',
            name='cidade',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='estudante',
            name='sexo',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='instituicao',
            name='telefone',
            field=models.CharField(max_length=14),
        ),
    ]
