# Generated by Django 4.2.5 on 2023-10-04 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_cursos_inscricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='is_institution',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='is_student',
            field=models.BooleanField(default=False),
        ),
    ]
