# Generated by Django 4.2.6 on 2023-10-27 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0019_instuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instuser',
            name='groups',
            field=models.ManyToManyField(related_name='inst_User', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='instuser',
            name='user_permissions',
            field=models.ManyToManyField(related_name='inst_User', to='auth.permission'),
        ),
    ]
