# Generated by Django 4.2.6 on 2023-10-27 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_instuser_groups_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='instUser',
        ),
    ]
