# Generated by Django 4.2.6 on 2023-10-27 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_delete_instuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='institution',
            field=models.CharField(default='univespteste', max_length=100),
            preserve_default=False,
        ),
    ]
