# Generated by Django 4.2.6 on 2023-10-27 18:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_remove_usuario_institution_alter_usuario_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursos',
            name='instituicao',
            field=models.ForeignKey(default='marcos', on_delete=django.db.models.deletion.CASCADE, to='core.instituicao'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instituicao',
            name='user',
            field=models.ForeignKey(default='marcos', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
