# Generated by Django 4.2.6 on 2023-10-27 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_cursos_instituicao_instituicao_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cursos',
            name='instituicao',
        ),
        migrations.RemoveField(
            model_name='instituicao',
            name='user',
        ),
    ]
