# Generated by Django 4.2 on 2023-09-08 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_instituicao_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cursos',
            name='categoria',
        ),
    ]
