# Generated by Django 4.0.6 on 2023-09-16 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_categorias'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instituicao',
            name='cnpj',
        ),
        migrations.AddField(
            model_name='instituicao',
            name='site',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
