# Generated by Django 4.2 on 2023-09-26 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_estudante_celular'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Categorias',
        ),
    ]
