# Generated by Django 4.2 on 2023-09-27 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_instituicao_cidade_alter_estudante_sexo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instituicao',
            name='telefone',
            field=models.CharField(max_length=15),
        ),
    ]
